config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, only: [:show]

  resources :attendances, only: [:create, :destroy]

  resources :events, only: [:index, :new, :create, :show]
  root to: 'events#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/attendance.rb
class Attendance < ApplicationRecord

    belongs_to :event
    belongs_to :attendee, class_name: 'User'
end

app/models/event.rb
class Event < ApplicationRecord
    scope :upcoming, -> {where("event_date >= ?", Time.now)}
    scope :past, -> {where("event_date <= ?", Time.now)}

    belongs_to :host, class_name: 'User'
    
    has_many :attendances
    has_many :attendees, through: :attendances
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :hosted_events, class_name: 'Event', foreign_key: 'host_id', dependent: :destroy

  has_many :attendances, foreign_key: 'attendee_id', dependent: :destroy
  has_many :attended_events, through: :attendances, source: :event
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/attendances_controller.rb
class AttendancesController < ApplicationController
    before_action :authenticate_user!

    def create
        event = Event.find(params[:id])
        attendance = Attendance.new(event_id: event.id, attendee_id: current_user.id, attending: true)
    
        if attendance.save
          redirect_to request.referrer and return
        end
    end

    def destroy
        Attendance.find_by(event_id: params[:id], attendee_id: current_user.id).destroy
        redirect_to request.referrer
    end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
    before_action :authenticate_user!, only: [:new, :create, :show]
    
    def index
        @events = Event.all
    end

    def new
        @event = Event.new
    end

    def create
        @event = current_user.hosted_events.build(event_params)

        if @event.save
            redirect_to :root and return
        end
        render :new
    end

    def show
        @event = Event.find(params[:id])
    end

    private
        def event_params
            params.require(:event).permit(:name, :location, :event_date, :host_id)
        end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    def show
        @attended_events = current_user.attended_events
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attendances_helper.rb
module AttendancesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/index.html.erb
<h1>All Events</h1>

<% upcoming = @events.upcoming%>
<% past = @events.past %>

<h2>Upcoming Events</h2>
    <% upcoming.each do |e| %>
        <div>
            <p><%= e.name %></p>
            <p><%= e.location %></p>
            <p><%= e.event_date %></p>
            <p>Host: <%= e.host.email %></p>
            <%= link_to 'More Details', event_path(e)%>
        </div>
    <% end %>

<h2>Past Events</h2>
    <% past.each do |e| %>
        <div>
            <p><%= e.name %></p>
            <p><%= e.location %></p>
            <p><%= e.event_date %></p>
            <p>Host: <%= e.host.email %></p>
            <p>Attendees: <%= e.attendees.count %>
        </div>
    <% end %>

app/views/events/new.html.erb
<h1>Create Event</h1>
<%= form_with model: @event do |f| %>
    <%= f.label :name, 'Name' %>
    <%= f.text_field :name %>

    <%= f.label :location, 'Location' %>
    <%= f.text_field :location %>

    <%= f.label :event_date, 'Date'%>
    <%= f.date_field :event_date %>

    <%= f.submit %>
<% end %>

app/views/events/show.html.erb
<p><%= @event.name %></p>
<p>Location: <%= @event.location %></p>
<p>Time: <%= @event.event_date %></p>
<p>Host: <%= @event.host.email %></p>
<p>Number of Attendees: <%= @event.attendees.count %></p>

<% if @event.host.id == current_user.id %>
    <p>You are <strong>hosting</strong> this event</p>
<% elsif Attendance.where(event: @event.id, attendee: current_user.id).exists? %>
    <%= button_to 'Unattend', attendance_path, params: {id: @event.id}, method: :delete %>
<% else %>
    <%= button_to 'Attend', attendances_path, params: {id: @event.id} %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrivateEvents</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= link_to 'Home', :root %>
    <%= link_to 'Sign Up', '/users/sign_up' unless user_signed_in? %>
    <%= link_to 'Sign Out', '/users/sign_out', data: { turbo_method: :delete } if user_signed_in? %>
    <%= link_to 'Create Event', '/events/new' if user_signed_in? %>
    <%= link_to 'Attending Events', '/users/show' if user_signed_in? %>
    <%= yield %>
  </body>
</html>

app/views/users/show.html.erb
<h1>Attended events</h1>

<% upcoming_events = @attended_events.where("event_date >= ?", Time.now)%>
<% old_events = @attended_events.where("event_date <= ?", Time.now)%>

<h2>Upcoming Events</h2>
    <p><%= 'No upcoming events' if  upcoming_events.empty? %></p>
    <% upcoming_events.each do |e| %>
        <p><%= e.name %></p>
        <p><%= e.location %></p>
        <p><%= e.event_date %></p>
    <% end %>

<h2>Past Events</h2>
    <% old_events.each do |e| %>
        <p><%= e.name %></p>
        <p><%= e.location %></p>
        <p><%= e.event_date %></p>
    <% end %>